-- AlterEnum
ALTER TYPE "RadarType" ADD VALUE 'FINIA';
ALTER TYPE "RadarType" ADD VALUE 'PORTFOLIO';
ALTER TYPE "RadarType" ADD VALUE 'RADAR_OPPORTUNITY';
ALTER TYPE "RadarType" ADD VALUE 'ACHIEVEMENT';
